plugins {
    id 'com.android.application' version '8.4.1'
    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false
}

android {
    namespace 'com.ali.iptv'
    compileSdk 34

    defaultConfig {
        applicationId "com.ali.iptv"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            // توجيه Gradle للبحث عن المانفيست داخل مجلد app
            manifest.srcFile 'app/AndroidManifest.xml'
            java.srcDirs = ['app/src/main/java', 'app/src', 'app']
            res.srcDirs = ['app/src/main/res', 'app/res']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
